name: Validate Structure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build
      
    - name: Run tests
      run: npm test
      continue-on-error: true
      
    - name: Validate structure
      run: npx ts-node scripts/validate-structure.ts
      
    - name: Check documentation is up to date
      run: |
        # Check if workspace files have been updated recently
        if [ -z "$(find workspace -name "*.md" -mtime -30)" ]; then
          echo "⚠️ Workspace documentation seems stale (not updated in 30 days)"
          exit 1
        fi
        
    - name: Lint code
      run: npm run lint
      continue-on-error: true
      
    - name: Type check
      run: npm run typecheck
      
    - name: Run demo to ensure it works
      run: npm run demo